spring.application.name=movie-booking-backend

# MySQL Database Setup
spring.datasource.url=jdbc:mysql://localhost:3306/movie_booking_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Nayak@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true