// src/mockData.js
export const mockMovies = [
  {
    movie_id: 1,
    title: "Avengers: Endgame",
    genre: "Cosmic / Action / Sci-Fi",
    tag: "Cosmic",
    rating: "4.9",
    offerText: "50% OFF up to $10",
    duration_minutes: 181,
    poster: "https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg",
    banner: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1200",
    synopsis: "After the devastating events of Infinity War, the remaining Avengers assemble once more to reverse Thanos' actions and restore balance to the universe.",
    shows: [{ show_id: 101, time: "11:00 AM", price: 15.00 }, { show_id: 102, time: "08:00 PM", price: 20.00 }]
  },
  {
    movie_id: 2,
    title: "The Avengers",
    genre: "Action / Sci-Fi / Team",
    tag: "Team",
    rating: "4.8",
    offerText: "BUY 1 GET 1 FREE",
    duration_minutes: 143,
    poster: "https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg",
    banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200",
    synopsis: "Earth's mightiest heroes must come together and learn to fight as a team to stop Loki and his alien army from enslaving humanity.",
    shows: [{ show_id: 201, time: "01:15 PM", price: 12.00 }, { show_id: 202, time: "06:45 PM", price: 15.50 }]
  },
  {
    movie_id: 3,
    title: "Iron Man 3",
    genre: "Tech / Action / Thriller",
    tag: "Tech",
    rating: "4.5",
    offerText: "Free Stark Energy Drink",
    duration_minutes: 130,
    poster: "https://upload.wikimedia.org/wikipedia/en/1/19/Iron_Man_3_poster.jpg",
    banner: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200",
    synopsis: "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
    shows: [{ show_id: 301, time: "10:30 AM", price: 14.00 }, { show_id: 302, time: "04:00 PM", price: 14.00 }]
  },
  {
    movie_id: 4,
    title: "Captain America: Civil War",
    genre: "Political / Action / Drama",
    tag: "Team",
    rating: "4.7",
    offerText: "No Convenience Fee",
    duration_minutes: 147,
    poster: "https://upload.wikimedia.org/wikipedia/en/9/9e/Captain_America_Civil_War_poster.jpg",
    banner: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200",
    synopsis: "Political involvement in the Avengers' affairs causes a deep rift between former allies Captain America and Iron Man.",
    shows: [{ show_id: 401, time: "12:00 PM", price: 13.50 }, { show_id: 402, time: "09:00 PM", price: 17.00 }]
  },
  {
    movie_id: 5,
    title: "Thor: Ragnarok",
    genre: "Cosmic / Comedy / Fantasy",
    tag: "Cosmic",
    rating: "4.8",
    offerText: "30% OFF on Snacks",
    duration_minutes: 130,
    poster: "https://upload.wikimedia.org/wikipedia/en/7/7d/Thor_Ragnarok_poster.jpg",
    banner: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=1200",
    synopsis: "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarok, the destruction of his world.",
    shows: [{ show_id: 501, time: "02:30 PM", price: 15.00 }, { show_id: 502, time: "07:30 PM", price: 18.00 }]
  },
  {
    movie_id: 6,
    title: "Doctor Strange",
    genre: "Mystic / Magic / Sci-Fi",
    tag: "Mystic",
    rating: "4.6",
    offerText: "Free IMAX Upgrade",
    duration_minutes: 115,
    poster: "https://upload.wikimedia.org/wikipedia/en/a/a1/Doctor_Strange_poster.jpeg",
    banner: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=1200",
    synopsis: "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
    shows: [{ show_id: 601, time: "11:45 AM", price: 12.50 }, { show_id: 602, time: "05:15 PM", price: 15.00 }]
  },
  {
    movie_id: 7,
    title: "Guardians of the Galaxy",
    genre: "Cosmic / Adventure / Space",
    tag: "Cosmic",
    rating: "4.7",
    offerText: "50% OFF up to $10",
    duration_minutes: 121,
    poster: "https://upload.wikimedia.org/wikipedia/en/b/b5/Guardians_of_the_Galaxy_poster.jpg",
    banner: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?w=1200",
    synopsis: "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
    shows: [{ show_id: 701, time: "03:00 PM", price: 14.00 }, { show_id: 702, time: "08:30 PM", price: 17.50 }]
  },
  {
    movie_id: 8,
    title: "Black Panther",
    genre: "Action / Sci-Fi / Cyberpunk",
    tag: "Tech",
    rating: "4.9",
    offerText: "Wakanda Welcome Gift",
    duration_minutes: 134,
    poster: "https://upload.wikimedia.org/wikipedia/en/d/d6/Black_Panther_%28film%29_poster.jpg",
    banner: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=1200",
    synopsis: "T'Challa, heir to the hidden kingdom of Wakanda, must step forward to lead his people into a new era while facing a challenger from his past.",
    shows: [{ show_id: 801, time: "01:00 PM", price: 15.00 }, { show_id: 802, time: "06:00 PM", price: 15.00 }]
  },
  {
    movie_id: 9,
    title: "Spider-Man: Homecoming",
    genre: "Action / Sci-Fi / Youth",
    tag: "Tech",
    rating: "4.6",
    offerText: "Student Pass Special",
    duration_minutes: 133,
    poster: "https://upload.wikimedia.org/wikipedia/en/f/f9/Spider-Man_Homecoming_poster.jpg",
    banner: "https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=1200",
    synopsis: "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man.",
    shows: [{ show_id: 901, time: "10:00 AM", price: 12.00 }, { show_id: 902, time: "04:30 PM", price: 14.50 }]
  },
  {
    movie_id: 10,
    title: "Captain Marvel",
    genre: "Cosmic / Action / Sci-Fi",
    tag: "Cosmic",
    rating: "4.4",
    offerText: "Flat $5 Cashback",
    duration_minutes: 123,
    poster: "https://upload.wikimedia.org/wikipedia/en/4/4e/Captain_Marvel_%28film%29_poster.jpg",
    banner: "https://images.unsplash.com/photo-1502134249126-9f3755a50d78?w=1200",
    synopsis: "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
    shows: [{ show_id: 1101, time: "02:00 PM", price: 14.00 }, { show_id: 1102, time: "09:30 PM", price: 18.50 }]
  },
  {
    movie_id: 11,
    title: "Avengers: Infinity War",
    genre: "Cosmic / Action / Tragedy",
    tag: "Cosmic",
    rating: "4.9",
    offerText: "Thanos Snapped Fees",
    duration_minutes: 149,
    poster: "https://upload.wikimedia.org/wikipedia/en/4/4d/Avengers_Infinity_War_poster.jpg",
    banner: "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=1200",
    synopsis: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation puts an end to the universe.",
    shows: [{ show_id: 1201, time: "11:30 AM", price: 16.00 }, { show_id: 1202, time: "08:15 PM", price: 21.00 }]
  },
  {
    movie_id: 12,
    title: "Iron Man",
    genre: "Tech / Origins / Action",
    tag: "Tech",
    rating: "4.9",
    offerText: "Legacy Discount 20%",
    duration_minutes: 126,
    poster: "https://upload.wikimedia.org/wikipedia/en/0/0c/Iron_Man_Marvel_Comic_Book_Poster_Art.jpg",
    banner: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=1200",
    synopsis: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    shows: [{ show_id: 1211, time: "09:00 AM", price: 10.00 }, { show_id: 1212, time: "03:00 PM", price: 13.00 }]
  }
]; 